name: Update .pot file 🌐

on:
  push:
    branches: [dev]
    paths:
      - "**/*.php"
      - "**/*.js"
  workflow_dispatch:


jobs:
  update-pot-file:
    uses: pressbooks/reusable-workflows/.github/workflows/update-pot.yml@main
    secrets: inherit
    with:
      domain: "parsedown-party"
      slug: "parsedown-party"
      package_name: "Parsedown Party"
      headers: '{"Report-Msgid-Bugs-To": "https://github.com/pressbooks/parsedown-party/issues"}'
